{% set name = "pymt_rafem" %}
{% set version = "0.1" %}
{% set build = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - numpy 1.11.*
    - cython
    - model_metadata
    - rafem

  run:
    - python
    - setuptools
    - pymt
    - rafem

test:
  requires:
    - bmi-tester
  imports:
    - pymt
    - rafem
  commands:
    - mmd-stage Rafem .
    - bmi-test rafem:Rafem --infile=rafem.txt

about:
  summary: Python package that wraps the rafem BMI.
  home: https://github.com/mcflugen/pymt_rafem
  license: MIT license
  license_file: LICENSE
  dev_url: https://github.com/mcflugen/pymt_rafem
